
package mx.ksms.engine.ce;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EngineCEService", targetNamespace = "http://ce.engine.ksms.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EngineCEService {


    /**
     * 
     * @param agRiesgoocupacion
     * @param solicitudId
     * @param rDIFMSPWULTCPT12
     * @param fecantigclicred
     * @param edad
     * @param renovacion
     * @param antigempleo
     * @param riesgogeografico
     * @param rCOBSLDPAS12
     * @param rEVOPAGOS3
     * @param agEstadocivil
     * @param agServicio
     * @param propmontoliberado
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "calculateDictamenDePerfil", targetNamespace = "http://ce.engine.ksms.mx/", className = "mx.ksms.engine.ce.CalculateDictamenDePerfil")
    @ResponseWrapper(localName = "calculateDictamenDePerfilResponse", targetNamespace = "http://ce.engine.ksms.mx/", className = "mx.ksms.engine.ce.CalculateDictamenDePerfilResponse")
    public String calculateDictamenDePerfil(
        @WebParam(name = "solicitudId", targetNamespace = "")
        String solicitudId,
        @WebParam(name = "riesgogeografico", targetNamespace = "")
        String riesgogeografico,
        @WebParam(name = "renovacion", targetNamespace = "")
        String renovacion,
        @WebParam(name = "R_DIFMS_PWULTCPT12", targetNamespace = "")
        Double rDIFMSPWULTCPT12,
        @WebParam(name = "R_EVOPAGOS3", targetNamespace = "")
        Double rEVOPAGOS3,
        @WebParam(name = "PROPMONTOLIBERADO", targetNamespace = "")
        Double propmontoliberado,
        @WebParam(name = "FECANTIGCLICRED", targetNamespace = "")
        Double fecantigclicred,
        @WebParam(name = "EDAD", targetNamespace = "")
        Integer edad,
        @WebParam(name = "ANTIGEMPLEO", targetNamespace = "")
        Integer antigempleo,
        @WebParam(name = "ag_riesgoocupacion", targetNamespace = "")
        String agRiesgoocupacion,
        @WebParam(name = "ag_estadocivil", targetNamespace = "")
        String agEstadocivil,
        @WebParam(name = "ag_servicio", targetNamespace = "")
        String agServicio,
        @WebParam(name = "R_COB_SLDPAS12", targetNamespace = "")
        Double rCOBSLDPAS12);

    /**
     * 
     * @param servicios
     * @param solicitudId
     * @param experienciaCrediticia
     * @param creditosLiquidados
     * @param edad
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "calculateDictamenDePoliticas", targetNamespace = "http://ce.engine.ksms.mx/", className = "mx.ksms.engine.ce.CalculateDictamenDePoliticas")
    @ResponseWrapper(localName = "calculateDictamenDePoliticasResponse", targetNamespace = "http://ce.engine.ksms.mx/", className = "mx.ksms.engine.ce.CalculateDictamenDePoliticasResponse")
    public String calculateDictamenDePoliticas(
        @WebParam(name = "solicitudId", targetNamespace = "")
        String solicitudId,
        @WebParam(name = "servicios", targetNamespace = "")
        String servicios,
        @WebParam(name = "EDAD", targetNamespace = "")
        Integer edad,
        @WebParam(name = "experiencia_crediticia", targetNamespace = "")
        boolean experienciaCrediticia,
        @WebParam(name = "creditos_liquidados", targetNamespace = "")
        int creditosLiquidados);

    /**
     * 
     * @param cantidadIntegrantesFamilia
     * @param solicitudId
     * @param creditosLiquidados
     * @param tipoDeVivienda
     * @param otrosIngresos
     * @param cadenaBc
     * @param renovacion
     * @param antigempleo
     * @param agEstadocivil
     * @param propmontoliberado
     * @param agRiesgoocupacion
     * @param cuotaCredito
     * @param porcentajeDedescuento
     * @param ingresosFijosMensuales
     * @param gastosDeAlquiler
     * @param rDIFMSPWULTCPT12
     * @param fecantigclicred
     * @param edad
     * @param ingresosVariablesMensuales
     * @param riesgogeografico
     * @param rCOBSLDPAS12
     * @param asalariado
     * @param experienciaCrediticia
     * @param rEVOPAGOS3
     * @param agServicio
     * @return
     *     returns mx.ksms.engine.ce.EngineCEDataOutput
     */
    @WebMethod
    @WebResult(name = "EngineCEDataOutput", targetNamespace = "")
    @RequestWrapper(localName = "calculateProb", targetNamespace = "http://ce.engine.ksms.mx/", className = "mx.ksms.engine.ce.CalculateProb")
    @ResponseWrapper(localName = "calculateProbResponse", targetNamespace = "http://ce.engine.ksms.mx/", className = "mx.ksms.engine.ce.CalculateProbResponse")
    public EngineCEDataOutput calculateProb(
        @WebParam(name = "solicitudId", targetNamespace = "")
        String solicitudId,
        @WebParam(name = "riesgogeografico", targetNamespace = "")
        String riesgogeografico,
        @WebParam(name = "renovacion", targetNamespace = "")
        String renovacion,
        @WebParam(name = "R_DIFMS_PWULTCPT12", targetNamespace = "")
        Double rDIFMSPWULTCPT12,
        @WebParam(name = "R_EVOPAGOS3", targetNamespace = "")
        Double rEVOPAGOS3,
        @WebParam(name = "PROPMONTOLIBERADO", targetNamespace = "")
        Double propmontoliberado,
        @WebParam(name = "FECANTIGCLICRED", targetNamespace = "")
        Double fecantigclicred,
        @WebParam(name = "EDAD", targetNamespace = "")
        Integer edad,
        @WebParam(name = "ANTIGEMPLEO", targetNamespace = "")
        Integer antigempleo,
        @WebParam(name = "ag_riesgoocupacion", targetNamespace = "")
        String agRiesgoocupacion,
        @WebParam(name = "ag_estadocivil", targetNamespace = "")
        String agEstadocivil,
        @WebParam(name = "ag_servicio", targetNamespace = "")
        String agServicio,
        @WebParam(name = "R_COB_SLDPAS12", targetNamespace = "")
        Double rCOBSLDPAS12,
        @WebParam(name = "ingresos_fijos_mensuales", targetNamespace = "")
        Double ingresosFijosMensuales,
        @WebParam(name = "ingresos_variables_mensuales", targetNamespace = "")
        Double ingresosVariablesMensuales,
        @WebParam(name = "otros_ingresos", targetNamespace = "")
        Double otrosIngresos,
        @WebParam(name = "cantidad_integrantes_familia", targetNamespace = "")
        Integer cantidadIntegrantesFamilia,
        @WebParam(name = "gastos_de_alquiler", targetNamespace = "")
        Double gastosDeAlquiler,
        @WebParam(name = "cuota_credito", targetNamespace = "")
        Double cuotaCredito,
        @WebParam(name = "tipo_de_vivienda", targetNamespace = "")
        Integer tipoDeVivienda,
        @WebParam(name = "asalariado", targetNamespace = "")
        boolean asalariado,
        @WebParam(name = "experiencia_crediticia", targetNamespace = "")
        boolean experienciaCrediticia,
        @WebParam(name = "creditos_liquidados", targetNamespace = "")
        int creditosLiquidados,
        @WebParam(name = "cadena_bc", targetNamespace = "")
        String cadenaBc,
        @WebParam(name = "porcentajeDedescuento", targetNamespace = "")
        Double porcentajeDedescuento);

    /**
     * 
     * @param solicitudId
     * @param cadenaBc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "save_cadena_bc")
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "save_cadena_bc", targetNamespace = "http://ce.engine.ksms.mx/", className = "mx.ksms.engine.ce.SaveCadenaBc")
    @ResponseWrapper(localName = "save_cadena_bcResponse", targetNamespace = "http://ce.engine.ksms.mx/", className = "mx.ksms.engine.ce.SaveCadenaBcResponse")
    public String saveCadenaBc(
        @WebParam(name = "solicitudId", targetNamespace = "")
        String solicitudId,
        @WebParam(name = "cadena_bc", targetNamespace = "")
        String cadenaBc);

}
