
package mx.ksms.engine.cl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EngineService", targetNamespace = "http://cl.engine.ksms.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EngineService {


    /**
     * 
     * @param agRiesgoocupacion
     * @param ingresosFijosMensuales
     * @param indicapasnovista
     * @param d1RConoe1ConOe
     * @param agMopPeorSis
     * @param rDSPTOCONSIS
     * @param cuotaMensualCredito
     * @param agPlazo
     * @param edad
     * @param ingresosVariablesMensuales
     * @param riesgogeografico
     * @param rCOBSLDPAS12
     * @param agEstadocivil
     * @param rCUOINGFU
     * @param agServicio
     * @param agPeriodicidad
     * @param rCONOE1CONOE
     * @param gastosMensuales
     * @param agHist12Hist24
     * @param antigvivienda
     * @return
     *     returns mx.ksms.engine.cl.EngineDataOutput
     */
    @WebMethod
    @WebResult(name = "EngineDataOutput", targetNamespace = "")
    @RequestWrapper(localName = "calculateProb", targetNamespace = "http://cl.engine.ksms.mx/", className = "mx.ksms.engine.cl.CalculateProb")
    @ResponseWrapper(localName = "calculateProbResponse", targetNamespace = "http://cl.engine.ksms.mx/", className = "mx.ksms.engine.cl.CalculateProbResponse")
    public EngineDataOutput calculateProb(
        @WebParam(name = "riesgogeografico", targetNamespace = "")
        String riesgogeografico,
        @WebParam(name = "ag_plazo", targetNamespace = "")
        Integer agPlazo,
        @WebParam(name = "ag_periodicidad", targetNamespace = "")
        String agPeriodicidad,
        @WebParam(name = "R_CUO_INGFU", targetNamespace = "")
        Double rCUOINGFU,
        @WebParam(name = "ag_riesgoocupacion", targetNamespace = "")
        String agRiesgoocupacion,
        @WebParam(name = "EDAD", targetNamespace = "")
        Integer edad,
        @WebParam(name = "R_COB_SLDPAS12", targetNamespace = "")
        Double rCOBSLDPAS12,
        @WebParam(name = "ag_estadocivil", targetNamespace = "")
        String agEstadocivil,
        @WebParam(name = "ag_servicio", targetNamespace = "")
        String agServicio,
        @WebParam(name = "INDICAPASNOVISTA", targetNamespace = "")
        String indicapasnovista,
        @WebParam(name = "ANTIGVIVIENDA", targetNamespace = "")
        Integer antigvivienda,
        @WebParam(name = "ag_hist12_hist24", targetNamespace = "")
        Double agHist12Hist24,
        @WebParam(name = "ag_mop_peor_sis", targetNamespace = "")
        Double agMopPeorSis,
        @WebParam(name = "R_DSPTOCON_SIS", targetNamespace = "")
        Double rDSPTOCONSIS,
        @WebParam(name = "d1_r_conoe1con_oe", targetNamespace = "")
        String d1RConoe1ConOe,
        @WebParam(name = "R_CONOE1CON_OE", targetNamespace = "")
        Double rCONOE1CONOE,
        @WebParam(name = "ingresos_fijos_mensuales", targetNamespace = "")
        Double ingresosFijosMensuales,
        @WebParam(name = "ingresos_variables_mensuales", targetNamespace = "")
        Double ingresosVariablesMensuales,
        @WebParam(name = "gastos_mensuales", targetNamespace = "")
        Double gastosMensuales,
        @WebParam(name = "cuota_mensual_credito", targetNamespace = "")
        Double cuotaMensualCredito);

}
